name: web_query_example
description: Example demonstrating DataQueryWidget usage
publish_to: 'none'

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1  
  http: ^1.2.0
  web_query:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
